'use client';
import Image from 'next/image';
import { useState } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Building2, Leaf, Pencil } from 'lucide-react';
import { restaurantInputSchema, restaurantSettingsSchema, type RestaurantInput } from '@dineflow/shared';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Editor, Field, FormActions, PageHeader, QueryState, useSetupMutation, useSetupQuery } from './shared';
import { ImageUpload } from './image-upload';

function SettingsForm({ restaurant, close }: { restaurant: RestaurantInput; close: () => void }) {
  const [uploading, setUploading] = useState(false);
  const { name, address, phone, logoUrl, timezone, serviceChargeBps, taxBps } = restaurant;
  const form = useForm<RestaurantInput>({ resolver: zodResolver(restaurantInputSchema), defaultValues: { name, address, phone, logoUrl, timezone, serviceChargeBps, taxBps } });
  const { register, control, formState: { errors } } = form;
  const save = useSetupMutation('/restaurant/settings', 'PATCH', close);
  return <form className="space-y-5" onSubmit={form.handleSubmit(input => save.mutate(input))}><Field label="Tên nhà hàng" error={errors.name?.message}><Input {...register('name')} maxLength={120} /></Field><Controller control={control} name="logoUrl" render={({ field }) => <ImageUpload value={field.value} onChange={field.onChange} onBusyChange={setUploading} label="Logo nhà hàng" />} /><Field label="Địa chỉ" error={errors.address?.message}><Input {...register('address')} maxLength={500} /></Field><Field label="Số điện thoại" error={errors.phone?.message}><Input {...register('phone')} type="tel" maxLength={30} /></Field><Field label="Múi giờ" error={errors.timezone?.message}><Input {...register('timezone')} placeholder="Asia/Ho_Chi_Minh" /></Field><p className="text-xs text-muted-foreground">Đơn vị tiền tệ: VND — Việt Nam Đồng.</p><div className="grid grid-cols-2 gap-4">{([{ key: 'serviceChargeBps', label: 'Phí dịch vụ (%)' }, { key: 'taxBps', label: 'Thuế (%)' }] as const).map(({ key, label }) => <Field key={key} label={label} error={errors[key]?.message}><Controller control={control} name={key} render={({ field }) => <Input type="number" min={0} max={100} step={0.01} name={field.name} ref={field.ref} onBlur={field.onBlur} value={Number.isNaN(field.value) ? '' : field.value / 100} onChange={event => field.onChange(event.target.value === '' ? NaN : Math.round(Number(event.target.value) * 100))} />} /></Field>)}</div><p className="rounded-xl border bg-white p-4 text-xs leading-6 text-muted-foreground">Phí và thuế được lưu theo cấu hình của nhà hàng, chính xác đến 0,01%.</p><FormActions pending={save.isPending || uploading} error={save.error} cancel={close} /></form>;
}
export function SettingsPage() {
  const query = useSetupQuery('/restaurant/settings', restaurantSettingsSchema);
  const [open, setOpen] = useState(false);
  const restaurant = query.data;
  return <div className="space-y-7"><PageHeader title="Thông tin nhà hàng" description="Một thông tin thống nhất cho đội ngũ và trải nghiệm của thực khách." action={restaurant && <Button onClick={() => setOpen(true)}><Pencil />Chỉnh sửa thông tin</Button>} /><QueryState pending={query.isPending} error={query.error} retry={query.refetch}>{restaurant && <div className="grid items-start gap-6 xl:grid-cols-[1.65fr_0.85fr]"><Card className="overflow-hidden"><div className="flex items-center gap-4 border-b p-6">{restaurant.logoUrl ? <Image unoptimized src={restaurant.logoUrl} width={48} height={48} alt="Logo nhà hàng" className="size-12 rounded-xl object-cover" /> : <span className="grid size-12 place-items-center rounded-xl bg-primary text-accent"><Building2 className="size-5" /></span>}<div><h2 className="text-lg font-semibold">{restaurant.name}</h2><p className="mt-1 text-xs text-muted-foreground">Không gian trải nghiệm ẩm thực</p></div></div><div className="space-y-7 p-6">{[{ title: 'Thông tin cơ bản', rows: [['Tên nhà hàng', restaurant.name], ['Địa chỉ', restaurant.address || 'Chưa cập nhật'], ['Số điện thoại', restaurant.phone || 'Chưa cập nhật']] }, { title: 'Định dạng & thanh toán', rows: [['Đơn vị tiền tệ', 'VND — Việt Nam Đồng'], ['Múi giờ', restaurant.timezone], ['Phí dịch vụ', `${restaurant.serviceChargeBps / 100}%`], ['Thuế', `${restaurant.taxBps / 100}%`]] }].map(group => <section key={group.title}><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-primary">{group.title}</h3><dl>{group.rows.map(([label, value]) => <div key={label} className="grid gap-2 border-b py-4 text-xs last:border-0 sm:grid-cols-2"><dt className="text-muted-foreground">{label}</dt><dd className="font-medium leading-6">{value}</dd></div>)}</dl></section>)}</div></Card><aside className="overflow-hidden rounded-2xl bg-primary text-white"><div className="relative h-44"><Image src="/images/dining-editorial.png" alt="" fill sizes="(min-width: 1280px) 25vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-b from-primary/10 to-primary" /></div><div className="px-6 pb-8"><div className="mb-5 flex items-center gap-2 text-xs text-accent"><Leaf className="size-4" />Nhịp phục vụ DineFlow</div><h2 className="editorial text-4xl leading-tight">Một không gian.<br /><span className="italic text-accent">Cùng một nhịp.</span></h2><p className="mt-5 text-xs leading-7 text-white/75">Từ bàn ăn đến căn bếp, cùng chăm chút những bữa ăn trọn vẹn.</p></div></aside></div>}</QueryState><Editor open={open} onOpenChange={setOpen} title="Chỉnh sửa thông tin nhà hàng">{open && restaurant && <SettingsForm restaurant={restaurant} close={() => setOpen(false)} />}</Editor></div>;
}
