import { expect, test } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const password = process.env.SEED_DEMO_PASSWORD;
if (!password) throw new Error('Thiếu SEED_DEMO_PASSWORD; chạy setup:env, migrations và seed trước browser tests');
const qaDir = resolve(__dirname, '../../../.local/qa');
mkdirSync(qaDir, { recursive: true });

test('desktop: login, database metrics, settings, refresh and logout', async ({ page, context }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/staff/dashboard');
  await expect(page).toHaveURL(/\/staff\/login$/);
  await expect(page.getByRole('heading', { name: 'Chào mừng trở lại', exact: true })).toBeVisible();
  await expect.poll(() => page.locator('img').evaluateAll(images => images.every(image => image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0))).toBe(true);
  await page.screenshot({ path: resolve(qaDir, 'login-desktop.png'), fullPage: true });
  await page.getByLabel('Email nhân viên', { exact: true }).fill('owner@dineflow.local');
  await page.getByLabel('Mật khẩu', { exact: true }).fill(password!);
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
  await expect(page).toHaveURL(/\/staff\/dashboard$/);
  await expect(page.getByTestId('metric-Bàn phục vụ')).toHaveText('10');
  await expect(page.getByTestId('metric-Danh mục món')).toHaveText('5');
  await expect(page.getByTestId('metric-Món trong thực đơn')).toHaveText('20');
  await expect(page.getByTestId('metric-Đội ngũ nhân viên')).toHaveText('5');
  await page.screenshot({ path: resolve(qaDir, 'dashboard-desktop.png'), fullPage: true });
  const cookies = await context.cookies();
  expect(cookies.filter(cookie => cookie.name.startsWith('df_')).every(cookie => cookie.httpOnly && cookie.sameSite === 'Lax')).toBeTruthy();
  await page.getByRole('navigation', { name: 'Menu chính' }).getByRole('link', { name: 'Thông tin nhà hàng' }).click();
  await expect(page.getByRole('heading', { name: 'Thông tin nhà hàng', exact: true })).toBeVisible();
  await expect(page.getByText('Thành phố Hồ Chí Minh', { exact: true })).toBeVisible();
  await page.screenshot({ path: resolve(qaDir, 'settings-desktop.png'), fullPage: true });
  await context.clearCookies({ name: 'df_access' });
  const refresh = page.waitForResponse(response => response.url().endsWith('/api/v1/auth/refresh') && response.status() === 200);
  await page.reload();
  await refresh;
  await expect(page.getByText('Thành phố Hồ Chí Minh', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Đăng xuất', exact: true }).click();
  await expect(page).toHaveURL(/\/staff\/login$/);
  await page.goto('/admin/settings');
  await expect(page).toHaveURL(/\/staff\/login$/);
  expect(errors).toEqual([]);
});

test('mobile: validation, password toggle, drawer and role restrictions', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/staff/login');
  await page.screenshot({ path: resolve(qaDir, 'login-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
  await expect(page.getByText('Email không hợp lệ', { exact: true })).toBeVisible();
  await page.getByLabel('Email nhân viên', { exact: true }).fill('waiter@dineflow.local');
  await page.getByLabel('Mật khẩu', { exact: true }).fill('incorrect');
  await page.getByRole('button', { name: 'Hiện mật khẩu' }).click();
  await expect(page.getByLabel('Mật khẩu', { exact: true })).toHaveAttribute('type', 'text');
  await page.getByRole('button', { name: 'Ẩn mật khẩu' }).click();
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Email hoặc mật khẩu không đúng' })).toBeVisible();
  await page.getByLabel('Mật khẩu', { exact: true }).fill(password!);
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
  await expect(page.getByTestId('metric-Bàn phục vụ')).toHaveText('10');
  await page.screenshot({ path: resolve(qaDir, 'dashboard-mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole('button', { name: 'Mở menu' }).click();
  await expect(page.getByRole('navigation', { name: 'Menu chính' })).toBeVisible();
  await expect(page.getByRole('navigation', { name: 'Menu chính' }).getByText('Thông tin nhà hàng')).toHaveCount(0);
  await page.getByRole('button', { name: 'Đóng menu', exact: true }).last().click();
  await page.goto('/admin/settings');
  await expect(page.getByRole('alert').filter({ hasText: 'Bạn không có quyền' })).toBeVisible();
  await page.getByRole('button', { name: 'Đăng xuất', exact: true }).click();
  await expect(page).toHaveURL(/\/staff\/login$/);
});
